### ISSUE TITLE
this.activeInputStream.end is not a function in AbstractIngestionEngine

### ISSUE THREAD

**Issue by chriszs** [tvkitchen/tv-kitchen#58]
#### Current Behavior

When I try to inherit from the AbstractIngestionEngine and use it to stream from a file (after fixing #57), I get:

```
/Users/chriszs/Desktop/work/tv-kitchen/src/components/ingestion/AbstractIngestionEngine.js:108
        this.activeInputStream.end();
                               ^

TypeError: this.activeInputStream.end is not a function
    at FileIngestionEngine.stop (/Users/chriszs/Desktop/work/tv-kitchen/src/components/ingestion/AbstractIngestionEngine.js:180:27)
    at /Users/chriszs/Desktop/work/tv-kitchen/src/components/ingestion/AbstractIngestionEngine.js:169:15
    at internal/util.js:392:14
    at finish (internal/streams/pipeline.js:174:7)
    at internal/util.js:392:14
    at internal/streams/pipeline.js:67:5
    at finish (internal/streams/pipeline.js:170:23)
    at internal/util.js:392:14
    at internal/streams/pipeline.js:67:5
    at finish (internal/streams/pipeline.js:170:23)
```

#### Input

```sh
yarn babel-node src/components/ingestion/test.js
```

```js
// src/components/ingestion/test.js
import 'module-alias/register'
import AbstractIngestionEngine from './AbstractIngestionEngine'

class FileIngestionEngine extends AbstractIngestionEngine {
	constructor(path) {
		super()

		this.path = path
	}

	path = null

	getInputStream = () => fs.createReadStream(this.path)
}

const engine = new FileIngestionEngine(__dirname + '/in.ts')

engine.start()
```

#### Expected Behavior
I expected it to not throw that error.

#### Possible Solutions
For a readable stream, there seems to be no `end()` (there is for writable streams). Appears it should be `destroy()`.

#### Related Issues
#57

**Comment by slifty** [comment]
Closed by #56
